language: java
addons:
  sonarcloud:
    organization: "alikhano-github"
    token: $SONAR_TOKEN
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
jdk:
  - oraclejdk8
